### ISSUE TITLE
Background color does not change with several emulators.

### ISSUE THREAD

**Issue by GotekSC** [deviantfero/wpgtk#142] opened 2019-03-14 09:20 UTC
Currently using urxvt, which works perfectly fine with wpg, but I was fed up with the unicode issues, and tried some other emulators, but all I tried had a similar problem. Their background color does not change with wpg:

+ alacritty
+ kitty
+ termite

There's a special case with `st` which changes BG color on initial startup with xresources and alpha patch on the config I put together. 
https://gitlab.com/GotekSC/st/blob/master/config.h
```
ResourcePref resources[] = {
		{ "background",   STRING,  &colorname[258] },
		{ "foreground",   STRING,  &colorname[257] },
		{ "cursorColor",  STRING,  &colorname[256] },
		{ "alpha",        FLOAT,   &alpha },
};
```
But I couldn't get it to change colors on the fly, only with new terminals.

**Comment by deviantfero** [comment] 2019-03-14 10:33
I will check this out once I get home from vacations, probably something to
do with VTE

**Comment by GotekSC** [comment] 2019-03-15 14:13
Thanks. Hope you're having a good time during the rest of the vacation!

**Comment by deviantfero** [comment] 2019-03-20 07:36
Hi i've submitted a fix today that let's you enable the VTE fix from pywal, please let me know if this fix works for you

**Comment by GotekSC** [comment] 2019-03-22 21:43
Enabling the fix makes it even worse, somehow.
+ alacritty
+ kitty
+ termite
+ st
all behave the same as before, but urxvt now does no longer change the bg color of the padding that's set with `URxvt*internalBorder: 20` in Xresources

**Comment by deviantfero** [comment] 2019-04-13 16:27
have you tried putting `(cat .config/wpg/sequences &)` in your shell configuartion? I've tried to reproduce this unsuccessfully in all the terminals you provided there.

**Comment by GotekSC** [comment] 2019-04-14 01:57
```
# Import colorscheme from 'wpgtk' asynchronously
# &   # Run the process in the background.
# ( ) # Hide shell job control messages.
(cat $HOME/.config/wpg/sequences &)
```

That is what I have in my `.zshrc`

**Comment by GotekSC** [comment] 2019-05-27 10:19
I just now noticed (never occured to me to test) that when I use `wpg -i wallpaper.jpg` it does work with all of the mentioned terminals.

**Comment by deviantfero** [comment] 2019-05-27 15:49
are you sure `wpg -i wallpaper.jpg` works with that? `-i` requires two arguments in `wpg`

**Comment by GotekSC** [comment] 2019-06-03 12:21
You're right, I mixed things up. `wal -i wallpaper.jpg` works. The point is, somehow wal manages to change background color with the mentioned terminals, while it works only on urxvt with wpg for me.

**Comment by deviantfero** [comment] 2019-08-25 05:33
I'm sorry for leaving you hanging there, are you still having this issue? there have been a few releases after this, but none directly address this issue, it would mean a lot to me if you could confirm you're still having this issue.

**Comment by jasperro** [comment] 2019-09-19 19:22
The issue is still here. It looks like pywal's sequences differ from the ones wpgtk produces; the pywal sequences file sets the terminal background but the wpgtk one doesn't. You can find the files in this gist: [https://gist.github.com/jasperro/3fe92c252da3dcbbca9e121f6102946b](https://gist.github.com/jasperro/3fe92c252da3dcbbca9e121f6102946b). The wpgtk one has one sequence less than the pywal one, could this be the terminal background sequence missing?

**Comment by deviantfero** [comment] 2019-09-19 19:29
@jasperro, do the sequences change if you turn the `vte` option on or off?

**Comment by jasperro** [comment] 2019-09-19 19:34
I updated the gist with the VTE option off, seems like it added some [20]'s but it still doesn't work. Also I forgot to mention I'm using sway wayland.

**Comment by deviantfero** [comment] 2019-09-19 19:36
I have not tested in wayland, could that be the issue in wayland?

**Comment by jasperro** [comment] 2019-09-19 19:37
Seems like the issue still persists on X11, weird, it used to work earlier.

**Comment by deviantfero** [comment] 2019-09-19 19:42
what version of `wpgtk` and `pywal` are you using? and a command to reproduce this consistently?

**Comment by jasperro** [comment] 2019-09-19 19:45
wpgtk: 6.0.9
pywal: 3.3.0

command: `wpg --theme solarized` and `wal --theme solarized`

**Comment by jasperro** [comment] 2019-09-19 19:51
When I added ]708;#073642\ to the wpgtk sequences file, it set the background correctly.

**Comment by deviantfero** [comment] 2019-09-19 19:51
This are the results from my end, same versions as you:

#### termite
![termite](https://imgur.com/oofl9aa.png)

#### st
![st](https://imgur.com/QIeEtcp.png)

#### alacritty
![alacritty](https://imgur.com/skLqGWi.png)

#### kitty
![kitty](https://imgur.com/ZUsAx1G.png)

and both my sequences are being generated equal, wpgtk and pywal, I'll post in a second

**Comment by deviantfero** [comment] 2019-09-19 19:52
If it's not much bother, could you try to do the following from console in python 3?
```
>>> import pywal
>>> pywal.__version___
```

**Comment by jasperro** [comment] 2019-09-19 19:54
it prints '3.3.0'

**Comment by deviantfero** [comment] 2019-09-19 19:57
here are my sequences:
https://gist.github.com/deviantfero/2e357648185758b0aaeae60684639ca3

what do these do for you? do they get the background working?

**Comment by jasperro** [comment] 2019-09-19 19:58
Yes, your files work fine on my machine, very weird.

**Comment by deviantfero** [comment] 2019-09-19 19:59
yeah, I can't seem to reproduce, has this always happened?, what happens if you re-install wpgtk? same thing?

**Comment by jasperro** [comment] 2019-09-19 20:01
Just reinstalled both pywal and wpgtk, same issue.

**Comment by deviantfero** [comment] 2019-09-19 20:02
```
[settings]
set_wallpaper = true
gtk = true
active = 0
light_theme = false
editor = urxvtc -e emacsclient -t --create-frame
execute_cmd = true
command = bash ~/.config/bspwm/bspwm_colors.sh
backend = wal
alpha = 100
auto_sort = true
auto_adjust = false
smart_sort = true
vte = true

[keywords]

```

this are my options, mind sharing yours?

**Comment by jasperro** [comment] 2019-09-19 20:03
[settings]
set_wallpaper = true
openbox = true
gtk = true
active = 1
tint2 = true
light_theme = false
editor = urxvt -e vim
execute_cmd = false
backend = wal
alpha = 20
auto_sort = true
smart_sort = true
automatic_auto_adjust = true
auto_adjust = true
vte = false
command = bash /home/jasperro/.scripts/wpgjasperpl.sh jasperpl

[keywords]
barfont = Ubuntu Condensed
terminalfont = Fira Code
hintstyle = slight
cursortheme = Breeze-Obsidian
gtktheme = FlatColor
gtkfont = Ubuntu, Regular
uifont = Ubuntu
icontheme = Papirus-Dark
terminalfontsize = 11
uifontsize = 11
rofifontsize = 13

**Comment by deviantfero** [comment] 2019-09-19 20:04
got it!, try setting alpha to `100`, I reproduced on my machine by setting it to 20!

**Comment by jasperro** [comment] 2019-09-19 20:05
Ah, that was the random [20] in the sequences file then! It works with 100, thanks!

**Comment by deviantfero** [comment] 2019-09-19 20:07
yep, that will only work with `urxvt` so it makes sense, I should be more clear about it, glad we figured it out, I'll close this issue now.

**Closed by deviantfero** 2019-09-19 20:07 UTC

**Comment by NGStaph** [comment] 2020-05-04 07:58
Hi, thanks for helping with my last issue. I have something similar to this. the wal command will cause all new terminals (kitty) open with the newer layout but the wpg command only updates the colorscheme of the currently open terminals. I have added the `(cat ~/.cache/wpg/sequences &)` command to my .zshrc file. here is my wpg.conf.

```
[settings]
set_wallpaper = true
gtk = true
active = 0
light_theme = false
editor = urxvt -e vim
execute_cmd = false
command = urxvt -e echo hi
backend = wal
alpha = 100
smart_sort = true
auto_adjust = false
reload = true

[keywords]
```

**Comment by NGStaph** [comment] 2020-05-04 08:40
what am I doing incorrectly? @deviantfero 

```
❯ wpg -m
[i] image         Using image Surface_Go.jpg.
[i] theme         Set theme to _home_jaym__config_wpg_wallpapers_Surface_Go_jpg_dark_wal__1.1.0.json.
[i] colors        Found cached colorscheme.
[i] sequences     Set terminal colors.
[i] export        Exported all files.
[i] export        Exported all user files.
[i] color         wrote: icon-step1
[i] color         wrote: gtk2
[i] color         wrote: gtk3.0
[i] color         wrote: dunstrc
[i] color         wrote: gtk3.20
[i] wallpaper     Set the new wallpaper.

~
❯ wal -i /home/jaym/Pictures/backgrounds/Surface\ Go.jpg
[I] image: Using image Surface Go.jpg.
[I] colors: Generating a colorscheme.
[I] colors: Using wal backend.
[I] colors: Generation complete.
[I] wallpaper: Set the new wallpaper.
[I] sequences: Set terminal colors.
[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.
```
