### ISSUE TITLE
Set button doesn't apply i3blocks background colour first time

### ISSUE THREAD

**Issue by kleshas** [deviantfero/wpgtk#114] opened 2018-11-21 04:48 UTC
wpg GUI.  Chose a wallpaper (top drop down), it auto-selects the colourscheme (second dropdown), then click Set.  Most colours change, and the wallpaper changes, but not the i3-bar colours defined in i3's config (i3.base) until the second click of the Set button.  The second click changes those colours, and everything is good, as far as I can tell, from the perspective of the colours.
[i3.base.zip](https://github.com/deviantfero/wpgtk/files/2602653/i3.base.zip)

**Comment by deviantfero** [comment] 2018-11-21 05:18
hi, thanks for oppening this issue, can i get your i3blocks.conf?

**Comment by kleshas** [comment] 2018-11-21 06:46
Here you go
[i3blocks.conf.zip](https://github.com/deviantfero/wpgtk/files/2602968/i3blocks.conf.zip)

**Comment by deviantfero** [comment] 2019-05-02 06:49
Is this still an issue in the current version?

**Comment by yuceltoluyag** [comment] 2019-08-18 03:47
yes sir

**Comment by amanjitsk** [comment] 2019-09-29 22:21
The issue is the order of the files in the function `xrdb` in `data/reload.py`. I fixed this issue by commenting out the system `.Xresources` file out (or alternatively, if you do need to keep that in, just switch the order of the files)

**Comment by deviantfero** [comment] 2019-10-14 07:35
@amanjitsk, no need to do that, it is actually a feature of `wpgtk`, if your `.Xresources` has colors defined in it, they will override those merged by `wpg` from the other file, at least that's the idea, can anyone confirm that this is the cause of the issue?

if you do not wish to have colors overriden, remove any color settings related from your `.Xresources` that affect the programs you're using.

**Closed** 2020-03-09 18:24 UTC
