### ISSUE TITLE
Wayland wallpaper 

### ISSUE THREAD

**Issue by niksingh710** [deviantfero/wpgtk#265] opened 2022-07-30 22:32 UTC
Wpg does not set wallpaper on Wayland

**Comment by kleshas** [comment] 2022-07-30 23:54
Try installing swaybg

**Comment by deviantfero** [comment] 2022-10-14 02:15
did this work?

**Comment by niksingh710** [comment] 2022-10-16 06:36
> did this work?

yep i have to manually set wallpaper using it 
actually i use `wbg` a minimal wayalnd wallpaper setting tool.
then i use wpg -ns $wallpaper to generate colorscheme
so it looks like
```
wbg $imgpath
wpg -ns $imgpath
```

will wallpaper setting feature will be added?

**Comment by VGrol** [comment] 2022-11-28 23:26
The problem is that wayland doesn't do wallpapers the same, 
for instance, wallpapers that stretch across the screen only "work" by splitting them up in three parts and setting them individually.
Some programs do this for you, like azote. 

Probably out of scope for WPGTK to implement though.
In the meantime, you could add it to your post-wpg.sh script.

**Comment by kleshas** [comment] 2024-02-22 17:36
This is how I do it under sway:
    bindsym $mod+Shift+w exec wpg -m && feh --bg-tile "$(< "${HOME}/.cache/wal/wal")" && cp $(cat ~/.cache/wal/wal) ~/.cache/wal/wal.jpg

**Comment by deviantfero** [comment] 2024-10-30 22:26
this is currently out of scope, I think like @VGrol said the best option would be to use a post script

**Closed by deviantfero** 2024-10-30 22:26 UTC
