### ISSUE TITLE
Wallpaper not setting (correctly)

### ISSUE THREAD

**Issue by domsch1988** [deviantfero/wpgtk#74] opened 2018-01-18 18:31 UTC
Setting the selected picture as a wallpaper is hit or miss for me. For one, i'm using two monitors and every wallpaper is automatically spanned across both. Can this be selectable (either span or same picture for either monitor)?
Also, some pictures aren't set as wallpapers all together or are only applied after several tries.

I currently work around that by running "nitrogen --restore" after setting the color scheme.

**Comment by deviantfero** [comment] 2018-01-18 23:00
I'm not able to reproduce, the first error, even with nitrogen installed. If you have no use for nitrogen, I'd recommend switching to `feh` for setting wallpapers, but please run wpg from the console and post the log when it fails to set the wallpaper, it might be helpful

Those features are not availabe since pywal's engine for setting wallpapers chooses the most suitable choice present in your machine, it would be hard and out of scope to support those options since it needs to remain compatible with most wallpapers choosers.

**Comment by deviantfero** [comment] 2018-01-19 00:01
I've updated my comment to cover all of your concerns, if this doesn't work for you, please let me know.

**Comment by domsch1988** [comment] 2018-01-19 10:00
Ok, this helped a ton. I needed to tweak some things though. In the Script you need to specify the "head=" option to address both monitors independently, else it just spans both monitors again. The end-result is:
```
#!/bin/bash
nitrogen --set-zoom-fill --head=0 ~/.wallpapers/$(wpg -c) &
nitrogen --set-zoom-fill --head=1 ~/.wallpapers/$(wpg -c)
```

In wpg i needed to give bash the full path, "~" didn't work for what ever reason. The full command thats working is:

`bash /home/dschlack/.themes/color_other/wall.sh`

With that, everything is working as expected. Thanks for the fast and helpful Feedback. I can't even express how much wpgtk simplified my setup.

**Comment by deviantfero** [comment] 2018-01-19 14:24
this is great, glad you got it to work and thanks for the details, I'll close this issue, when I start working on the wiki (for better and more detailed instructions) I'll make sure to include this as an optional tip.

**Closed by deviantfero** 2018-01-19 14:24 UTC
