### ISSUE TITLE
gtk error (ensure surface for gicon)

### ISSUE THREAD

**Issue by tmathmeyer** [deviantfero/wpgtk#14] opened 2016-07-19 04:00 UTC
this is what happens when I click the "add" button:
you might be missing a dependency, but I am not a python guy so I can't say for sure

```
ted  ~  wpg
[]
CURRENT WALLPAPER: /home/ted/.wallpapers/.current
Adding...

(wpg.py:12499): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
/usr/bin/wpg: line 2: 12499 Aborted                 (core dumped) /usr/bin/wpgtk/src/wpg.py
 ted  ~  
```

**Comment by deviantfero** [comment] 2016-07-19 04:31
which distro are you using?

**Comment by deviantfero** [comment] 2017-07-03 00:27
was not able to reproduce, so i'll close this issue.

**Closed by deviantfero** 2017-07-03 00:27 UTC
