### ISSUE TITLE
[Question] How would I restore colorschemes on bspwm ?

### ISSUE THREAD

**Issue by Waynekosimoto** [deviantfero/wpgtk#100] opened 2018-07-02 00:21 UTC
It's not really an issue, but more of a question. I'm not sure how I should I be restoring my color scheme properly because I linked the wp-init.sh to my /usr/bin/ and just added ` wp-init.sh &` to my bspwmrc. However this doesn't work, but if I do wp-init.sh in a terminal it works perfectly.

**Comment by deviantfero** [comment] 2018-07-02 00:54
maybe there's another way to call it from bspwmrc? try calling it directly

`bash ~/.config/wpg/wp-init.sh`

let me know how it goes

**Comment by Waynekosimoto** [comment] 2018-07-06 03:10
It didn't work :/

**Comment by king-gheedorah** [comment] 2018-07-17 09:52
Tested with my bspwmrc, did not work. Tested with .xinitrc, also did not work. v 5.2.2. I outputted the wpg colors.json and replaced the wal colors.json, then ran wal -R through .xinitrc to sync. This works ok, but sucks when I change theme.

**Comment by deviantfero** [comment] 2018-07-17 14:59
could you provide an extract from your`bspwmrc` and your `.xinitrc` where `wpg-init.sh` is called?

**Comment by deviantfero** [comment] 2018-07-17 15:16
I think I've found a reason for this bug, do you have an `.Xresources` file?

**Comment by king-gheedorah** [comment] 2018-07-17 23:28
Ah, what an oversight. My bad. Unfortunately I still cannot call the script without running it directly from a terminal emulator. If the issue is resolved for you, then maybe it is in my own config files.

~/.config/bspwm/bspwmrc
> #! /bin/sh
> sxhkd &
> bash "$HOME/.config/wpg/wp_init.sh" &
> bspc monitor HDMI-0 -n 1 -d I II III IV
> bspc monitor DVI-I-0 -n 2 -d V VI VII VIII IX X

~/.xinitrc
> #!/bin/sh
> xrdb ~/.Xresources &
> terminator &
> compton --config ~/.compton.conf --vsync opengl -b &
> bash "$HOME/.config/wpg/wp_init.sh" &

~/.Xresources
> Xcursor.theme: capitaine-cursors

**Comment by deviantfero** [comment] 2018-07-18 00:15
hmm, I understand, something along this lines should appear in that output:
```sh
[inf] image         Using image bluepinkpattern.png.
[inf] colors        Found cached colorscheme.
[inf] sequences     Set terminal colors.
[inf] wallpaper     Set the new wallpaper.
[inf] export        Exported css.
[inf] export        Exported shell.
[inf] export        Exported xresources.
```

**Comment by king-gheedorah** [comment] 2018-07-18 01:53
Sorry, I missed that it runs as a separate command after. Should have posted the following:

> ~ 
➜ sh ~/.config/bspwm/bspwmrc
monitor: Invalid descriptor found in 'HDMI-0'.
monitor: Invalid descriptor found in 'DVI-I-0'.
config: normal_border_color: Invalid value: ''.
config: active_border_color: Invalid value: ''.
config: focused_border_color: Invalid value: ''.
config: Unknown setting: 'presel_border_color'.
Could not grab key 36 with modfield 64: the combination is already grabbed.
Could not grab key 36 with modfield 80: the combination is already grabbed.
... 
~ 
➜ [inf] image         Using image alps-blurred.jpg.
[inf] colors        Found cached colorscheme.
[inf] sequences     Set terminal colors.
[inf] wallpaper     Set the new wallpaper.
[inf] export        Exported css.
[inf] export        Exported shell.
[inf] export        Exported xresources.

The "..." is just a series of the same message for different keys

I'll let you know when I fix it!

**Comment by deviantfero** [comment] 2018-07-18 01:58
please do, keep in mind that if you're not using an .Xresources terminal you also need to load your sequences via `(cat ~/.config/wpg/sequences &)` on shell startup

**Comment by deviantfero** [comment] 2018-07-18 02:35
lol, we were lost for a little while there,
and thanks for the soda/coffe!

I'll close this issue

**Closed by deviantfero** 2018-07-18 02:35 UTC
