### ISSUE TITLE
When wpg is ran it yields bad interpreter error 

### ISSUE THREAD

**Issue by androvix** [deviantfero/wpgtk#24] opened 2016-11-22 16:23 UTC
Below is the full error. I installed via `install.sh` and `installaur.sh` since the latter actually makes the themes change in real time. Im running Ubuntu 16.10 64bit version. Please advise! The version looks awesome! Especially the the colorize gtk feature.
`bash: /usr/local/bin/wpg: /bin/env: bad interpreter: No such file or directory`
Update!
If I run `python3 wpg` it runs! However, the wallpaper and theme and tint2 wont change. When the I set the wallpaper this is what I get `Traceback (most recent call last):
  File "/home/michael/wpgtk/wpgtk/wpg.py", line 155, in on_set_clicked
    self.pixbuf_sample = GdkPixbuf.Pixbuf.new_from_file_at_size( path + colorscheme_sample, width=500, height=500 )
GLib.Error: g-file-error-quark: Failed to open file '/home/michael/.wallpapers/.forestcomfy.jpg.sample.png': No such file or directory (4)`

**Comment by deviantfero** [comment] 2016-11-22 16:47
you should be able to install it only using the 'install.sh', and I have adressed that error now, it and about that wallpaper, did you just put it in the folder? or use the 'add' button or command?

**Comment by androvix** [comment] 2016-11-22 17:02
Yes the add button put the file in /.wallpapers/ I did not have to do that manually. The wallpaper wont set and the themes are still static. wpg now launches it but it still doesnt function.

**Comment by deviantfero** [comment] 2016-11-22 17:06
execute it from console so you can get the output and paste the output of when you add the same image here, don't worry i'll make sure it works.

**Comment by androvix** [comment] 2016-11-22 17:17
heres the output of `wpg -l` `:: not installed by AUR
forestcomfy.jpg  wpg.conf`'
And the output of `wpg -s forestcomfy.jpg`:
`:: not installed by AUR
:: Setting forestcomfy.jpg as background
ln: failed to access '/home/michael/.wallpapers/.forestcomfy.jpg.colors': No such file or directory
xrdb: No such file or directory
xrdb: can't open file '/home/michael/.wallpapers/.forestcomfy.jpg.Xres'
:: Done
[Errno 2] No such file or directory: '/home/michael/.wallpapers/.forestcomfy.jpg.Xres'
(2, 'No such file or directory')
/home/michael/.wallpapers/.forestcomfy.jpg.Xres
[Errno 2] No such file or directory: '/home/michael/.wallpapers/.forestcomfy.jpg.Xres'
(2, 'No such file or directory')
/home/michael/.wallpapers/.forestcomfy.jpg.Xres
FG: 4a828f
BG: 28464c
ERR:: file forestcomfy.jpg not found
`
The wallpaper is set! but the themes are stagnant.

**Comment by androvix** [comment] 2016-11-22 17:19
wpg -l yields `:: not installed by AUR
forestcomfy.jpg  greenboom.jpg	wpg.conf`

wpg -s forestcomfy.jpg

`:: not installed by AUR
:: Setting forestcomfy.jpg as background
ln: failed to access '/home/michael/.wallpapers/.forestcomfy.jpg.colors': No such file or directory
xrdb: No such file or directory
xrdb: can't open file '/home/michael/.wallpapers/.forestcomfy.jpg.Xres'
:: Done
[Errno 2] No such file or directory: '/home/michael/.wallpapers/.forestcomfy.jpg.Xres'
(2, 'No such file or directory')
/home/michael/.wallpapers/.forestcomfy.jpg.Xres
[Errno 2] No such file or directory: '/home/michael/.wallpapers/.forestcomfy.jpg.Xres'
(2, 'No such file or directory')
/home/michael/.wallpapers/.forestcomfy.jpg.Xres
FG: 4a828f
BG: 28464c
ERR:: file forestcomfy.jpg not found
`
The wallpaper is set but themes are unchanged.

**Comment by deviantfero** [comment] 2016-11-22 18:16
could you post the output to:
```
wpg -a /full/path/to/forestcomfy.jpg
```
?

thank you and sorry to ask you so many outputs but i've not been able to replicate this error

**Comment by androvix** [comment] 2016-11-22 18:56
Output for the first
`.greenboom.jpg.Xres  .            forestcomfy.jpg        wpg.conf  ..
greenboom.jpg        .tmp.colors  .greenboom.jpg.colors  .current
`
and the second
`:: not installed by AUR
:: Generating ./home/michael/Downloads/forestcomfy.jpg.colors and ./home/michael/Downloads/forestcomfy.jpg.Xres in /home/michael/.wallpapers
python2: can't open file '/usr/local/bin/py/color_detect.py': [Errno 2] No such file or directory
:: Done
`

**Comment by deviantfero** [comment] 2016-11-22 20:23
i know what the issue is, i'll let you know when I fix it, i'm working on it

**Comment by androvix** [comment] 2016-11-22 20:28
Thank you! I'll await your next response.

**Comment by deviantfero** [comment] 2016-11-22 21:13
Did it work for you? It should be fixed now

**Comment by androvix** [comment] 2016-11-22 23:30
Its still not working when i re-install it.

**Comment by deviantfero** [comment] 2016-11-22 23:34
Did you re-add the image, could you post the log? I recreated the error on my machine, by installing via the 'install.sh' script and then trying to add an image, and fixed the error, it was the call to a script whose directory had changed, right now i'm no longer getting the error.

```
$ wpg -a ~/Pictures/wallpapers/boat.jpg
:: not installed by AUR
:: Generating ./home/fernando/Pictures/wallpapers/boat.jpg.colors and ./home/fernando/Pictures/wallpapers/boat.jpg.Xres in /home/fernando/.wallpapers
/home/fernando/Pictures/wallpapers/boat.jpg
:: Done
```

**Comment by androvix** [comment] 2016-11-22 23:37
Wait, i add the py folder to /usr/local/bin/ and now it works. From what I could see from the error it was missing that folder in that place.

**Comment by deviantfero** [comment] 2016-11-23 00:14
you already had the /py/ folder but it was under /usr/local/bin/wpgtk, i've updated everything so the correct path is used and you shouldn't need to do that, anyway as proof, here's both methods of installation running perfectly fine on a fresh install. i'd recommend you to re-clone and re-install.

```sh
$ wpg -a 2016-11-21-161128_464x135_scrot.png
:: not installed by AUR
:: Generating .2016-11-21-161128_464x135_scrot.png.colors and .2016-11-21-161128_464x135_scrot.png.Xres in /home/fernando/.wallpapers
/usr/local/bin/
2016-11-21-161128_464x135_scrot.png
:: Done
```

```sh
$ wpg -a 2016-11-21-161128_464x135_scrot.png
:: installed by AUR
:: Generating .2016-11-21-161128_464x135_scrot.png.colors and .2016-11-21-161128_464x135_scrot.png.Xres in /home/fernando/.wallpapers
/usr/bin/
2016-11-21-161128_464x135_scrot.png
:: Done
```

**Closed by deviantfero** 2016-11-23 00:14 UTC
